basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = 'basic_app'

urlpatterns = [
    path('register/',views.register,name='register')
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():

        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
from django.shortcuts import render

from basic_app.forms import UserProfileInfoForm, UserForm 


# Create your views here.

def index(request):
    return render (request,'basic_app/index.html')

def register(request):

    registered = False

    if request.method =='POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form =UserProfileInfoForm()

    return render (request, 'basic_app/registration.html', {'user_form':user_form},{'profile_form': profile_form},{'registered':registered})

templates/basic_app/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">

                    <li><a class="navabr-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a> </li>

                </ul>

            </div>
        </nav>

        <div class="container">
            {% block body_block %} {% endblock %}
        </div>


    </body>
</head>

</html>

templates/basic_app/index.html
<!DOCTYPE html>{% extends "basic_app/base.html" %} {% block body_block %}
<div class="container">
    <h1>Django level 5</h1>
</div>
{% endblock %}

templates/basic_app/registration.html
{% extends "basic_app/base.html" %} 
{% load static %} 
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here</h1>
            <h3>Just fill out the form.</h3>

            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %} {{ user_form.as_p }} {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
             </form>

        {% endif %}

    </div>

</div>

{% endblock %}
</body>

</html>